# Generated by Django 5.1.1 on 2024-09-13 10:25

import django.db.models.deletion
import resto.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.CharField(default=resto.models.generate_id, max_length=255, primary_key=True, serialize=False, unique=True)),
                ('card_number', models.CharField(max_length=255)),
                ('card_type', models.CharField(max_length=255)),
                ('is_default', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.CharField(default=resto.models.generate_id, max_length=255, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('available_stock', models.IntegerField()),
                ('category', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.CharField(default=resto.models.generate_id, max_length=255, primary_key=True, serialize=False, unique=True)),
                ('default_address', models.TextField(max_length=400)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.CharField(default=resto.models.generate_id, max_length=255, primary_key=True, serialize=False, unique=True)),
                ('payment_method', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resto.paymentmethod')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resto.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resto.user')),
            ],
        ),
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.CharField(default=resto.models.generate_id, max_length=255, primary_key=True, serialize=False, unique=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resto.order')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resto.user')),
            ],
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resto.user'),
        ),
    ]
