# Generated by Django 5.1.1 on 2024-09-23 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resto', '0002_alter_user_managers_remove_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=255, unique=True),
        ),
    ]
