# Generated by Django 5.1.1 on 2024-09-24 01:14

import django.db.models.deletion
import resto.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resto', '0003_alter_user_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.CharField(default=resto.models.generate_id, max_length=255, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.CharField(default=resto.models.generate_id, max_length=255, primary_key=True, serialize=False, unique=True)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resto.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resto.product')),
            ],
        ),
    ]
