# Generated by Django 5.1.1 on 2025-06-23 20:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resto', '0008_product_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='location',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('hire', 'hire'), ('freelance', 'freelance')], default='freelancer', max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='address_default',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=255)),
                ('experience', models.IntegerField(default=1)),
                ('hourly_rate', models.FloatField()),
                ('languages', models.CharField(max_length=255)),
                ('Bio', models.TextField()),
                ('skills', models.TextField()),
                ('education', models.TextField()),
                ('website_link', models.CharField(max_length=255)),
                ('linkdeln_link', models.CharField(max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
